//Auth actions types
export const AUTHENTICATE_WITH_EMAIL = "AUTHENTICATE_WITH_EMAIL";
export const AUTHENTICATE_WITH_GOOGLE = "AUTHENTICATE_WITH_GOOGLE";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAIL = "AUTHENTICATION_FAIL";
export const SIGNUP_WITH_EMAIL = "SIGNUP_WITH_EMAIL";
export const SIGNUP_WITH_GOOGLE = "SIGNUP_WITH_GOOGLE";
export const CHANGE_USER = "CHANGE_USER";
export const LOG_OUT = "LOG_OUT";
